<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e95d654f-3135-46fd-8e40-ee1c01b337a3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="6.3.2" />
    <PackageReference Include="WolverineFx.Http" Version="5.30.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleStore.Application\SimpleStore.Application.csproj" />
    <ProjectReference Include="..\SimpleStore.Infrastructure\SimpleStore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
